# ==============================================================================================
# Script: trend_analysis.R
# Description: Advanced statistical modeling on customer feedback data.
#              Identifies statistically significant trends in product ratings over time
#              using Time Series forecasting (ARIMA) and linear regression.
# Author: Hajimammad Aliyev
# ==============================================================================================

# Load necessary libraries
suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(forecast)
  library(arrow)
})

# 1. Load Parquet Data (Generated by Python ETL)
# In production, this path is passed dynamically via CLI arguments
data_path <- "../data/processed/feedback_cleaned.parquet"
if(file.exists(data_path)) {
  df <- read_parquet(data_path)
} else {
  stop("Data file not found. Ensure Python ETL pipeline has run.")
}

# 2. Time Series Aggregation
monthly_trends <- df %>%
  mutate(month_date = as.Date(paste0(year_month, "-01"))) %>%
  group_by(month_date, product_id) %>%
  summarize(
    avg_rating = mean(rating, na.rm = TRUE),
    review_count = n(),
    .groups = 'drop'
  ) %>%
  filter(review_count >= 30) # Filter out low-volume statistical noise

# 3. ARIMA Forecasting (Example for Top Product)
top_product <- monthly_trends %>% filter(product_id == 'P-100')
if(nrow(top_product) > 12) {
  ts_data <- ts(top_product$avg_rating, frequency = 12)
  fit <- auto.arima(ts_data)
  forecast_res <- forecast(fit, h = 6) # Forecast next 6 months
  
  # Export forecast plots for Power BI ingestion or Markdown reports
  png("../docs/product_p100_forecast.png", width=800, height=600)
  plot(forecast_res, main="6-Month Rating Forecast for P-100")
  dev.off()
}

# 4. Statistical Significance Testing
# Is the drop in rating from Q1 to Q2 statistically significant?
q1_data <- df %>% filter(year_month %in% c("2025-01", "2025-02", "2025-03"))$rating
q2_data <- df %>% filter(year_month %in% c("2025-04", "2025-05", "2025-06"))$rating

t_test_result <- t.test(q1_data, q2_data)

# Log results
cat("================ T-Test Results ================\n")
cat("P-Value:", t_test_result$p.value, "\n")
if(t_test_result$p.value < 0.05) {
  cat("Conclusion: The difference in ratings between Q1 and Q2 is statistically significant.\n")
} else {
  cat("Conclusion: No statistically significant difference detected.\n")
}
